name = "SemiringFactorizations"
uuid = "10cb580f-a957-468a-9a4c-664b3154882c"
license = "MIT"
version = "0.0.1"
authors = ["Richard Samuelson <rsamuelson@ufl.edu>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TropicalGEMM = "a4ad3063-64a7-4bad-8738-34ed09bc0236"
TropicalNumbers = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"

[compat]
AbstractTrees = "0.4"
CliqueTrees = "1.12.2"
Graphs = "1"
LinearAlgebra = "1"
SparseArrays = "1"
TropicalGEMM = "0.2.0"
TropicalNumbers = "0.6.3"
julia = "1.10"
